### ISSUE TITLE
Bug in gitignore led to storage/ appears in repo

### ISSUE THREAD

**Issue by edwios** [ElliottDyson/OSGA#15]
Storage is not supposed to be part of the repo, at least not belong to the source. To properly fix it:

https://github.com/edwios/generative_agents/commit/fd4174b8707072456e227de089513feead2589e3

**Comment by ElliottDyson** [comment]
> Storage is not supposed to be part of the repo, at least not belong to the source. To properly fix it:
> 
> https://github.com/edwios/generative_agents/commit/fd4174b8707072456e227de089513feead2589e3
> 

How certain of this are you? It's where the base simulations are started from and where the new forks off of the base simulations are saved to.

What is the proposed method to replace it with?

**Comment by ElliottDyson** [comment]
No matter. I understand now, the current example versions will continue to exist, but if we run new forked simulations they will also be uploaded if not deleted. I'll make this change and push it.
