### ISSUE TITLE
Why is it still connecting to OpenAI?

### ISSUE THREAD

**Issue by BZBY** [ElliottDyson/OSGA#34]
After running 'run 66,' the backend is throwing an error
`---
  0%|                                                                                           | 0/66 [00:00<?, ?it/s]INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-19' coro=<ReverieServer.start_server() done, defined at D:\github\OSGA\main\reverie\backend_server\reverie.py:338> exception=AuthenticationError("Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-11111***************************************1111. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}")>
Traceback (most recent call last):
  File "D:\github\OSGA\main\reverie\backend_server\reverie.py", line 453, in start_server
    results = await self.run_async_movements()
  File "D:\github\OSGA\main\reverie\backend_server\reverie.py", line 335, in run_async_movements
    results = await asyncio.gather(*tasks)
  File "D:\github\OSGA\main\reverie\backend_server\reverie.py", line 323, in process_persona_async
    return await loop.run_in_executor(executor, self.process_persona, persona_name)
  File "D:\Programm\anconda\envs\llm_310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\github\OSGA\main\reverie\backend_server\reverie.py", line 306, in process_persona
    next_tile, pronunciation, description = persona.move(
  File "D:\github\OSGA\main\reverie\backend_server\persona\persona.py", line 221, in move
    perceived = self.perceive(maze)
  File "D:\github\OSGA\main\reverie\backend_server\persona\persona.py", line 108, in perceive
    return perceive(self, maze)
  File "D:\github\OSGA\main\reverie\backend_server\persona\cognitive_modules\perceive.py", line 147, in perceive
    event_embedding = get_embedding(desc_embedding_in)
  File "D:\github\OSGA\main\reverie\backend_server\persona\prompt_template\gpt_structure.py", line 283, in get_embedding
    return openai_client.embeddings.create(input=[text], model=model).data[0].embedding
  File "D:\Programm\anconda\envs\llm_310\lib\site-packages\openai\resources\embeddings.py", line 113, in create
    return self._post(
  File "D:\Programm\anconda\envs\llm_310\lib\site-packages\openai\_base_client.py", line 1200, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "D:\Programm\anconda\envs\llm_310\lib\site-packages\openai\_base_client.py", line 889, in request
    return self._request(
  File "D:\Programm\anconda\envs\llm_310\lib\site-packages\openai\_base_client.py", line 980, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-11111***************************************1111. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}`

please help me. thanks.

**Comment by FennFlyer** [comment]
Yeah, this is trying to grab embeddings from OpenAI.

**Comment by FennFlyer** [comment]
Found it: you need to uncomment line 17 in `main\reverie\backend_server\persona\prompt_template\gpt_structure.py`.

**Comment by ElliottDyson** [comment]
Sorry about this, it's correct that it is attempting to obtain embeddings from OpenAI still, we're working on alternatives such as sentence transformers or similar embedding models for this.

**Comment by ElliottDyson** [comment]
This issue has been closed. If you are still having this issue, please feel free to reopen.
